### ISSUE TITLE
安装好是正常的，重启后就不正常了，不知道怎么回事

### ISSUE THREAD

**Issue by haijunjiang** [xiaotian45123/ansible-k8s10x_and_k8s11x#7]
kubectl get nodes 提示连不上服务
其中node04有几个服务没起来
[root@node04 ~]# netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1052/master         
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      947/sshd            
tcp6       0      0 ::1:25                  :::*                    LISTEN      1052/master         
tcp6       0      0 :::2375                 :::*                    LISTEN      940/dockerd         
tcp6       0      0 :::22                   :::*                    LISTEN      947/sshd

**Comment by xiaotian45123** [comment]
node04节点不是master角色，不能再node04上执行kubectl get nodes这些命令，只能在master角色节点上执行这些命令

**Comment by haijunjiang** [comment]
你们重启服务器后，k8s还能正常使用吗？

**Comment by haijunjiang** [comment]
我又重启了几遍，现在的情况是master能执行kubectl 命令了，但是节点数少了
[root@node02 ~]# kubectl get nodes
NAME      STATUS    ROLES     AGE       VERSION
node01    Ready     master    6d        v1.11.0
node02    Ready     master    6d        v1.11.0
node03    Ready     master    6d        v1.11.0
只显示master
运行的容器好像也少了

[root@node02 ~]# kubectl -n kube-system get po -o wide
NAME                             READY     STATUS    RESTARTS   AGE       IP              NODE
coredns-86d9549d45-brf7t         1/1       Running   2          6d        10.244.1.6      node02
coredns-86d9549d45-pq59z         1/1       Running   2          6d        10.244.1.7      node02
kube-apiserver-node01            1/1       Running   1          2d        10.205.65.201   node01
kube-apiserver-node02            1/1       Running   2          6d        10.205.65.202   node02
kube-apiserver-node03            1/1       Running   2          1m        10.205.65.203   node03
kube-controller-manager-node01   1/1       Running   1          2d        10.205.65.201   node01
kube-controller-manager-node02   1/1       Running   3          6d        10.205.65.202   node02
kube-controller-manager-node03   1/1       Running   2          1m        10.205.65.203   node03
kube-flannel-ds-amd64-4g299      1/1       Running   2          6d        10.205.65.201   node01
kube-flannel-ds-amd64-4hgtk      1/1       Running   2          6d        10.205.65.203   node03
kube-flannel-ds-amd64-jr6r4      1/1       Running   4          6d        10.205.65.202   node02
kube-proxy-5fqww                 1/1       Running   2          6d        10.205.65.203   node03
kube-proxy-m77fw                 1/1       Running   2          6d        10.205.65.202   node02
kube-proxy-ptzvg                 1/1       Running   1          6d        10.205.65.201   node01
kube-scheduler-node01            1/1       Running   2          2d        10.205.65.201   node01
kube-scheduler-node02            1/1       Running   2          6d        10.205.65.202   node02
kube-scheduler-node03            1/1       Running   2          1m        10.205.65.203   node03

**Comment by haijunjiang** [comment]
能不能简单给一个各个节点的作用，分别跑了什么服务在上面

**Comment by xiaotian45123** [comment]
主机名称     	IP	                备注
node01	192.168.150.181	        master  and etcd
node02	192.168.150.182	        master  and etcd
node03	192.168.150.183	        master  and etcd
node04	192.168.150.184	        node
slb-179	192.168.150.179       	haproxy+keepalived
slb-180	192.168.150.180	        haproxy+keepalived
	    192.168.150.186	            VIP
如果不知道master和node节点是做什么用的，这个你得系统学习一下Kubernetes的相关知识
